#!/bin/sh

MY_LOCAL_DIR=`pwd`
cd ${MY_LOCAL_DIR}


###################################################################################################
if [ -x ${MY_LOCAL_DIR}/tdmServerD ]
then 
	mv ${MY_LOCAL_DIR}/tdmServerD ${MY_LOCAL_DIR}/bak/tdmServerD
	sed /'TDM_SERVERD_DIR\s*='/c\
TDM_SERVERD_DIR=${MY_LOCAL_DIR} ${MY_LOCAL_DIR}/bak/tdmServerD > ${MY_LOCAL_DIR}/tdmServerD
	chmod 777 ${MY_LOCAL_DIR}/tdmServerD
fi



###################################################################################################
if [ -x ${MY_LOCAL_DIR}/tdmServer.sh ]
then 
	mv ${MY_LOCAL_DIR}/tdmServer.sh ${MY_LOCAL_DIR}/bak/tdmServer.sh
	sed /'TDM_SERVER_DIR\s*='/c\
TDM_SERVER_DIR=${MY_LOCAL_DIR} ${MY_LOCAL_DIR}/bak/tdmServer.sh > ${MY_LOCAL_DIR}/tdmServer.sh
	chmod 777 ${MY_LOCAL_DIR}/tdmServer.sh
fi

cp -f ${MY_LOCAL_DIR}/tdmServer.sh /etc/init.d/
sudo update-rc.d tdmServer.sh defaults

echo "tdmServer install is OK!"

# End
