#!/bin/sh

TDM_SERVERD_DIR=/home/SubServer/TerminalDeviceManage

PS="ps aux"

while :
do
	tdmServerD_ret=" "
        tdmServerD_ret=`${PS} | grep bin/tdm | grep -v grep`
	if [ -z "${tdmServerD_ret}" ]
	then
		if [ -x ${TDM_SERVERD_DIR}/bin/tdm ]
             	then
			${TDM_SERVERD_DIR}/bin/tdm >> ${TDM_SERVERD_DIR}/logs/log.txt  
	     	fi
     	fi

	sleep 2
done

#end

